# Generated by Django 5.1.1 on 2024-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
