# Generated by Django 5.1.1 on 2024-11-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0002_diploma_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='diplomas_taken',
        ),
        migrations.CreateModel(
            name='UserDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmark.diploma')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diplomas', to='landmark.userprofile')),
            ],
        ),
    ]
