# Generated by Django 5.1.1 on 2024-11-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0003_remove_diploma_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10),
            preserve_default=False,
        ),
    ]
