# Generated by Django 5.1.1 on 2024-11-04 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0004_diploma_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='isonline',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='online', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='marco', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diploma',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserDiplomaSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('selected_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('date_selected', models.DateTimeField(default=django.utils.timezone.now)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmark.diploma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmark.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserDiploma',
        ),
    ]
