# Generated by Django 5.1.1 on 2024-11-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0005_diploma_isonline_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiplomaselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_selections', to='landmark.userprofile'),
        ),
    ]
