# Generated by Django 5.1.1 on 2024-11-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0006_alter_userdiplomaselection_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diploma',
            old_name='mode',
            new_name='is_online',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='isonline',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='diploma',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.CreateModel(
            name='SelectedDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('taken_on', models.DateTimeField(auto_now_add=True)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_users', to='landmark.diploma')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_diplomas', to='landmark.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserDiplomaSelection',
        ),
    ]
