# Generated by Django 5.1.1 on 2024-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0007_rename_mode_diploma_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
