# Generated by Django 5.1.1 on 2024-11-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0009_alter_diploma_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='image',
            field=models.ImageField(upload_to='diplomas/'),
        ),
    ]
