# Generated by Django 5.1.1 on 2024-11-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0010_alter_diploma_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
