# Generated by Django 5.1.1 on 2024-11-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0011_alter_diploma_price_alter_diploma_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='is_online',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
    ]
