# Generated by Django 5.1.1 on 2024-11-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0013_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
