# Generated by Django 5.1.1 on 2024-11-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0015_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='module',
            field=models.IntegerField(default=0),
        ),
    ]
