# Generated by Django 5.1.1 on 2024-11-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0016_diploma_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='module',
        ),
    ]
