# Generated by Django 5.1.1 on 2024-11-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0018_diploma_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diploma',
            old_name='module',
            new_name='module_count',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_content', models.TextField(blank=True, null=True)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='landmark.diploma')),
            ],
        ),
    ]
