# Generated by Django 5.1.1 on 2024-11-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0019_rename_module_diploma_module_count_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='content',
        ),
    ]
