# Generated by Django 5.1.1 on 2024-11-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0020_remove_diploma_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='sub_content',
            field=models.TextField(blank=True, help_text='Write each bullet point on a new line.', null=True),
        ),
    ]
