# Generated by Django 5.1.1 on 2024-11-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0021_alter_module_sub_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='module_count',
            field=models.IntegerField(default=0),
        ),
    ]
