# Generated by Django 5.1.1 on 2024-11-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0022_alter_diploma_module_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='price',
        ),
        migrations.AddField(
            model_name='diploma',
            name='price_egp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in Egyptian Pounds (EGP)', max_digits=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diploma',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in U.S. Dollars (USD)', max_digits=1000000),
            preserve_default=False,
        ),
    ]
