# Generated by Django 5.1.1 on 2024-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0023_remove_diploma_price_diploma_price_egp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255000),
        ),
    ]
