# Generated by Django 5.1.1 on 2024-11-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0024_alter_module_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='sub_content',
        ),
        migrations.AddField(
            model_name='diploma',
            name='session_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255000)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='landmark.module')),
            ],
        ),
    ]
