# Generated by Django 5.1.1 on 2024-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0025_remove_module_sub_content_diploma_session_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='content',
            field=models.TextField(blank=True, help_text='Write each bullet point on a new line.', null=True),
        ),
    ]
