# Generated by Django 5.1.1 on 2024-11-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0027_module_sub_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='sub_content',
            new_name='sessions',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
