# Generated by Django 5.1.1 on 2024-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0028_rename_sub_content_module_sessions_delete_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='session_count',
        ),
        migrations.AddField(
            model_name='module',
            name='session_count',
            field=models.IntegerField(default=0),
        ),
    ]
