# Generated by Django 5.1.1 on 2024-11-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0029_remove_diploma_session_count_module_session_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='session_count',
        ),
    ]
