# Generated by Django 5.1.1 on 2024-11-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0032_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
