# Generated by Django 5.1.1 on 2024-11-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0033_userprofile_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_token',
        ),
    ]
