# Generated by Django 5.1.1 on 2024-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0034_remove_userprofile_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
