# Generated by Django 5.1.1 on 2024-11-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0036_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Marco Maher', max_length=255),
            preserve_default=False,
        ),
    ]
