# Generated by Django 5.1.1 on 2024-11-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0037_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
