# Generated by Django 5.1.1 on 2024-11-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0039_myprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
