# Generated by Django 5.1.1 on 2024-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0040_remove_userprofile_email_delete_myprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
