# Generated by Django 5.1.1 on 2024-11-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0041_userprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pertner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partner/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team/')),
                ('email_link', models.EmailField(blank=True, max_length=255, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
