# Generated by Django 5.1.1 on 2024-11-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0042_pertner_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pertner',
            new_name='Partner',
        ),
    ]
