# Generated by Django 5.1.1 on 2024-11-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0043_rename_pertner_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='diploma',
            field=models.CharField(default='Unknown Program', max_length=255),
            preserve_default=False,
        ),
    ]
