# Generated by Django 5.1.1 on 2024-11-20 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0045_trainingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diploma',
            old_name='calendar',
            new_name='end_course',
        ),
        migrations.AddField(
            model_name='diploma',
            name='start_course',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
