# Generated by Django 5.1.1 on 2024-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0046_rename_calendar_diploma_end_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='material_pdf',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/material'),
        ),
        migrations.AddField(
            model_name='module',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='material_pdf',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/module/material'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='image',
            field=models.ImageField(upload_to='diplomas/images'),
        ),
    ]
