# Generated by Django 5.1.1 on 2024-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0047_diploma_material_pdf_module_link_module_material_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
