# Generated by Django 5.1.1 on 2024-11-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0048_module_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
