# Generated by Django 5.1.1 on 2024-11-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0050_alter_module_options_module_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
