# Generated by Django 5.1.1 on 2024-11-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0051_alter_module_options_remove_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
