# Generated by Django 5.1.1 on 2024-11-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0052_diploma_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='rating',
        ),
    ]
