# Generated by Django 5.1.1 on 2024-11-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0053_remove_diploma_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecteddiploma',
            name='level',
        ),
    ]
