# Generated by Django 5.1.1 on 2024-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0054_remove_selecteddiploma_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecteddiploma',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
