# Generated by Django 5.1.1 on 2024-11-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0055_selecteddiploma_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('question', models.TextField(verbose_name='Your Question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diploma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_queries', to='landmark.diploma', verbose_name='Choose Diploma')),
            ],
            options={
                'verbose_name': 'Contact Us Entry',
                'verbose_name_plural': 'Contact Us Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
