# Generated by Django 5.1.1 on 2024-11-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0056_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
