# Generated by Django 5.1.1 on 2024-11-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0057_contactus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='diploma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='landmark.diploma'),
            preserve_default=False,
        ),
    ]
