# Generated by Django 5.1.1 on 2024-11-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0058_alter_contactus_diploma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
