# Generated by Django 5.1.1 on 2024-11-26 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0059_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('question', models.TextField(verbose_name='Your Question')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmark.diploma')),
            ],
            options={
                'verbose_name': 'Contact Us Entry',
                'verbose_name_plural': 'Contact Us Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
