# Generated by Django 5.1.1 on 2024-11-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0060_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='price_egp',
            field=models.DecimalField(decimal_places=2, help_text='Price in Egyptian Pounds (EGP)', max_digits=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, help_text='Price in U.S. Dollars (USD)', max_digits=1000000, null=True),
        ),
    ]
