# Generated by Django 5.1.1 on 2024-11-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0062_alter_diploma_price_egp_alter_diploma_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='image',
            field=models.ImageField(blank=True, upload_to='diplomas/images'),
        ),
    ]
