# Generated by Django 5.1.1 on 2024-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0063_alter_diploma_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='course_duration_months',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course duration in months', max_digits=5, null=True),
        ),
    ]
