# Generated by Django 5.1.1 on 2024-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0064_diploma_course_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='course_duration_months',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Course duration in months', max_digits=5),
            preserve_default=False,
        ),
    ]
