# Generated by Django 5.1.1 on 2024-11-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0065_alter_diploma_course_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
