# Generated by Django 5.1.1 on 2024-11-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0066_diploma_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='level',
        ),
    ]
