# Generated by Django 5.1.1 on 2024-11-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0067_remove_diploma_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='selecteddiploma',
            name='mode',
        ),
    ]
