# Generated by Django 5.1.1 on 2024-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0068_remove_diploma_is_online_remove_selecteddiploma_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='course_duration_months',
            field=models.IntegerField(help_text='Course duration in months'),
        ),
    ]
