# Generated by Django 5.1.1 on 2024-11-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0069_alter_diploma_course_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='landmark/images/user1.png', null=True, upload_to='profiles/'),
        ),
    ]
