# Generated by Django 5.1.1 on 2024-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0072_alter_diploma_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='material_pdf',
            field=models.FileField(null=True, upload_to='diplomas/material'),
        ),
    ]
