# Generated by Django 3.2.25 on 2024-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0073_alter_diploma_material_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='sission_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
