# Generated by Django 3.2.25 on 2024-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0074_diploma_sission_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='graduation/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Training Gallery/')),
            ],
        ),
    ]
