# Generated by Django 3.2.25 on 2024-12-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0075_graduationimages_traininggallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='instructor_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
